networks:
  node:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - node
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always

  users: 
    build: 
      context: ./users
      args:
        - ENV=local
      dockerfile: Dockerfile
    container_name: users
    ports:
      - "9001:9001"
    volumes:
      - ./users/src:/var/www/html
      - /var/www/html/node_modules
    networks:
      - node
  blogs:
    build: 
      context: ./blogs
      args:
        - ENV=local
      dockerfile: Dockerfile
    container_name: blogs
    ports:
      - "9002:9002"
    volumes:
      - ./blogs/src:/var/www/html
      - /var/www/html/node_modules
    networks:
      - node
